"""Rustoo research app — a local browser front-end for the backtester.

    .venv/bin/streamlit run app/app.py        (or ./run_app.sh)

Runs only on this machine (127.0.0.1, no telemetry; see .streamlit/config.toml).
Every button runs one of the command-line tools in scripts/ and shows its
output, so each run is recorded in the run registry and can be reproduced
from the terminal with the command shown on the page.
"""
from __future__ import annotations

import json
import sys
from datetime import date, datetime, timezone
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app import helpers as h  # noqa: E402
from backtest.costs import SCENARIOS  # noqa: E402
from backtest.registry import RunRegistry  # noqa: E402
from backtest.splits import load_splits  # noqa: E402
from src.strategy.signals import STRATEGIES  # noqa: E402

REPO = h.REPO_ROOT
st.set_page_config(page_title="Rustoo research", page_icon="📈", layout="wide")

PAGES = ["Overview", "Data import", "Backtest", "Robustness", "Run history", "Paper bot"]


def live_config() -> dict:
    return yaml.safe_load((REPO / "config" / "strategy.yaml").read_text())


def run_and_show(argv: list[str], label: str) -> tuple[int, str]:
    """Run a script, streaming its output into an expandable log."""
    st.code(h.display_command(argv), language="bash")
    box = st.status(label, expanded=True)
    log = box.empty()
    lines: list[str] = []

    def on_line(line: str) -> None:
        lines.append(line.rstrip())
        log.code("\n".join(lines[-25:]), language="text")

    code, output = h.stream(argv, on_line)
    box.update(label=f"{label}: {'done' if code == 0 else 'failed'}", state="complete" if code == 0 else "error",
               expanded=code != 0)
    return code, output


def embed_report(path: Path, height: int = 1400) -> None:
    if not path.exists():
        st.warning(f"Report not found: {path}")
        return
    st.caption(f"Report file: `{path}` (open it directly in a browser for full screen)")
    # Reports are generated by this repo's own code (trusted), never from uploads.
    st.iframe(path, height=height)


def source_picker(key: str) -> Path | None:
    sources = h.data_sources()
    if not sources:
        st.error("No market data yet. Download it once: `.venv/bin/python scripts/download_binance_history.py`, "
                 "or import files on the Data import page.")
        return None
    label = st.selectbox("Data source", list(sources), key=key)
    return sources[label]


def period_picker(key: str, allow_custom: bool = True) -> dict:
    splits = load_splits()
    options = ["train", "validation", "test (holdout)"] + (["custom range"] if allow_custom else [])
    labels = {"train": f"train ({splits['train'].start:%Y-%m-%d} → {splits['train'].end:%Y-%m-%d})",
              "validation": f"validation ({splits['validation'].start:%Y-%m-%d} → {splits['validation'].end:%Y-%m-%d})",
              "test (holdout)": f"test / holdout (from {splits['test'].start:%Y-%m-%d}) — already used once",
              "custom range": "custom date range"}
    choice = st.radio("Period", options, index=1, format_func=labels.get, key=f"{key}_split", horizontal=False)
    out = {"split": {"test (holdout)": "test", "custom range": "custom"}.get(choice, choice), "use_holdout": False}
    if out["split"] == "custom":
        c1, c2 = st.columns(2)
        out["start"] = c1.date_input("From (UTC)", date(2025, 3, 1), key=f"{key}_start")
        out["end"] = c2.date_input("To (exclusive)", date(2025, 5, 1), key=f"{key}_end")
        if pd.Timestamp(out["end"], tz="UTC") > splits["test"].start:
            out["use_holdout"] = st.checkbox("This range reaches into the holdout — I understand", key=f"{key}_ho")
    if out["split"] == "test":
        st.warning("The holdout was already used for the final evaluation. Looking again is fine, "
                   "but don't change the strategy based on what you see here.")
        out["use_holdout"] = st.checkbox("I understand — use the holdout", key=f"{key}_ho")
    return out


# -- pages ------------------------------------------------------------------------------------

def page_overview() -> None:
    st.title("Rustoo research")
    st.write("A local front-end for the backtester. Everything runs on this machine; each run is recorded and "
             "reproducible from the terminal.")
    c1, c2, c3 = st.columns(3)
    sources = h.data_sources()
    c1.metric("Data sources", len(sources))
    c2.metric("Recorded runs", len(RunRegistry().list(limit=1000)))
    snap = h.bot_snapshot()
    c3.metric("Paper bot equity", f"${snap['equity'].equity.iloc[-1]:,.0f}" if snap and len(snap["equity"]) else "—")
    st.subheader("Workflow")
    st.markdown(
        "1. **Data import** — upload Excel/CSV, check the validation report (Binance history is already available).\n"
        "2. **Backtest** — pick data, period, strategy, coins, parameters and costs; run; read the report.\n"
        "3. **Robustness** — stress tests, Monte Carlo, regimes, parameter maps, random-entry test.\n"
        "4. **Run history** — reopen, compare or reproduce any earlier run.\n"
        "5. **Paper bot** — what the running paper bot is doing.")
    cfg = live_config()["trend_vol_target"]
    st.subheader("Live strategy settings (config/strategy.yaml)")
    st.json(cfg)
    for label, path in sources.items():
        pairs = h.pairs_in(path)
        if "BTC/USD" in pairs:
            start, end, bars = h.source_span(path, "BTC/USD")
            st.caption(f"{label}: {len(pairs)} pairs; BTC {start:%Y-%m-%d} → {end:%Y-%m-%d} ({bars:,} bars)")
        else:
            st.caption(f"{label}: {len(pairs)} pairs")


def page_import() -> None:
    st.title("Data import")
    st.write("Upload Excel (.xlsx/.xls) or CSV files with OHLC(V) columns. Columns are detected automatically; "
             "each file gets a validation report. Clean files become a data source for backtests.")
    files = st.file_uploader("Files", type=["xlsx", "xls", "csv"], accept_multiple_files=True)
    c1, c2, c3 = st.columns(3)
    source = c1.text_input("Dataset name", "uploads", help="Imported files land in data/imported/<name>/")
    tz = c2.selectbox("Timezone of the timestamps", ["UTC", "Asia/Kolkata", "Asia/Hong_Kong", "Australia/Sydney",
                                                     "Europe/London", "America/New_York"],
                      help="Bloomberg exports use your terminal's local time (IST for the ones checked so far).")
    labelled = c3.radio("Each row's time marks the bar's", ["start", "end"], horizontal=True,
                        help="Bloomberg intraday bars are labelled by start; Binance by open time (start).")
    c4, c5, c6 = st.columns(3)
    mode = c4.selectbox("When rows fail validation", ["warn", "reject", "remove", "repair"],
                        help="warn: import only if no errors · reject: never import files with errors · "
                             "remove: drop bad rows · repair: only drop exact duplicate rows")
    ref_opts = {"none": None, **{k: v for k, v in h.data_sources().items() if "Binance" in k}}
    reference = c5.selectbox("Cross-check prices against", list(ref_opts), index=min(1, len(ref_opts) - 1))
    symbol = c6.text_input("Pair (only if one file and the name doesn't say)", "", placeholder="e.g. BTC/USD")
    mapping_txt = st.text_input("Explicit column mapping (optional)", "", placeholder="timestamp=Date close=PX_LAST")
    not_crypto = st.checkbox("Not crypto (don't require 24/7 trading)")

    if st.button("Import and validate", type="primary", disabled=not files):
        upload_dir = REPO / "data" / "raw" / "uploads" / datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        upload_dir.mkdir(parents=True, exist_ok=True)
        paths = []
        for f in files:
            p = upload_dir / Path(f.name).name
            p.write_bytes(f.getbuffer())
            paths.append(p)
        mapping = dict(m.split("=", 1) for m in mapping_txt.split() if "=" in m)
        argv = h.import_argv(paths, {"source": source, "tz": tz, "labelled_by": labelled,
                                     "mode": mode, "symbol": symbol.strip() or None, "mapping": mapping,
                                     "reference": ref_opts[reference], "not_crypto": not_crypto})
        run_and_show(argv, "Importing")
        report = REPO / "data" / "imported" / source / "validation_report.json"
        if report.exists():
            show_import_report(json.loads(report.read_text()))

    lib = REPO / "data" / "imported" / "library.json"
    if lib.exists():
        st.subheader("Dataset library")
        rows = json.loads(lib.read_text())["datasets"]
        st.dataframe(pd.DataFrame(rows)[["source", "file", "symbol", "status", "timeframe", "start", "end", "bars", "imported_at"]],
                     width="stretch", hide_index=True)


def show_import_report(results: list[dict]) -> None:
    st.subheader("Validation report")
    mark = {"imported": "✓ imported", "imported_with_warnings": "⚠ imported with warnings", "rejected": "✕ rejected"}
    st.dataframe(pd.DataFrame([{"file": r["file"], "pair": r["symbol"], "status": mark[r["status"]], "timeframe": r["timeframe"],
                                "start": (r["start"] or "")[:16], "end": (r["end"] or "")[:16], "bars": r["bars"],
                                "rows removed": r["rows_removed"]} for r in results]), width="stretch", hide_index=True)
    for r in results:
        with st.expander(f"{mark[r['status']]} — {r['file']} ({r['symbol']})"):
            for issue in r["issues"]:
                fn = {"error": st.error, "warning": st.warning}.get(issue["severity"], st.info)
                fn(f"**{issue['code']}** — {issue['message']}")
            for note in r.get("notes", []):
                st.caption(note)
            if r.get("output"):
                df = pd.read_parquet(r["output"])
                fig = go.Figure(go.Scatter(x=df.index, y=df.close, name="close"))
                fig.update_layout(height=260, margin=dict(l=40, r=10, t=20, b=30))
                st.plotly_chart(fig, width="stretch")
                st.dataframe(pd.concat([df.head(3), df.tail(3)]), width="stretch")


def params_form(strategy: str, pairs: list[str], key: str) -> dict:
    live = live_config()
    defaults = h.strategy_defaults(STRATEGIES[strategy], live.get(strategy))
    params = {}
    cols = st.columns(3)
    for i, (name, default) in enumerate(defaults.items()):
        col = cols[i % 3]
        if name == "assets":
            pre = [p for p in (default or []) if p in pairs] or pairs[:2]
            params[name] = col.multiselect("Coins", pairs, pre, key=f"{key}_{name}")
        elif name == "symbol":
            params[name] = col.selectbox("Coin", pairs, index=pairs.index("BTC/USD") if "BTC/USD" in pairs else 0, key=f"{key}_{name}")
        elif isinstance(default, bool):
            params[name] = col.checkbox(name, default, key=f"{key}_{name}")
        elif isinstance(default, int):
            params[name] = int(col.number_input(name, value=default, step=1, key=f"{key}_{name}"))
        elif isinstance(default, float):
            params[name] = float(col.number_input(name, value=default, step=0.01, format="%.4f", key=f"{key}_{name}"))
    return params


def page_backtest() -> None:
    st.title("Backtest")
    live = live_config()
    policy = live.get("execution_policy", {})
    source = source_picker("bt_source")
    if source is None:
        return
    pairs = h.pairs_in(source)
    left, right = st.columns([1, 1])
    with left:
        period = period_picker("bt")
    with right:
        strategy = st.selectbox("Strategy", sorted(STRATEGIES), index=sorted(STRATEGIES).index("trend_vol_target"))
        st.caption("Defaults are the live settings from config/strategy.yaml for trend_vol_target, "
                   "otherwise the function's own defaults. Lookbacks are in hourly bars.")
    st.subheader("Parameters")
    params = params_form(strategy, pairs, "bt")

    st.subheader("Costs and execution")
    c1, c2, c3, c4 = st.columns(4)
    costs = c1.selectbox("Cost preset", list(SCENARIOS), index=list(SCENARIOS).index("base"))
    preset = SCENARIOS[costs]
    fee = c2.number_input("Taker fee (bps)", value=preset.taker_fee * 1e4, step=1.0)
    slip = c3.number_input("Slippage (bps)", value=preset.slippage_bps, step=1.0)
    spread = c4.number_input("Spread (bps, full)", value=preset.spread_bps, step=1.0)
    c5, c6, c7, c8 = st.columns(4)
    maker = c5.slider("Maker share of fills", 0.0, 1.0, preset.maker_fill_probability, 0.05)
    exec_price = c6.selectbox("Fill at next bar's", ["open", "close"], index=0 if policy.get("execution_price", "open") == "open" else 1)
    latency = c7.number_input("Latency (bars)", min_value=1, value=1, step=1)
    capital = c8.number_input("Capital ($)", value=100_000.0, step=10_000.0)
    c9, c10, c11 = st.columns(3)
    is_live = strategy == "trend_vol_target"
    band = c9.number_input("Rebalance band (weight)", value=float(policy.get("rebalance_threshold", 0.05)) if is_live else 0.0,
                           step=0.01, format="%.3f")
    hours = c10.multiselect("Exact rebalance at UTC hours", list(range(24)),
                            default=list(policy.get("rebalance_hours_utc", [0])) if is_live else [])
    seeds = c11.number_input("Random-entry baseline seeds", min_value=0, value=20, step=5)
    benchmarks = st.multiselect("Benchmarks", pairs, [p for p in ("BTC/USD", "ETH/USD") if p in pairs])

    if strategy == "trend_vol_target" and not params.get("assets"):
        st.error("Pick at least one coin.")
        return
    needs_holdout = period["split"] == "test" or (
        period["split"] == "custom" and pd.Timestamp(period["end"], tz="UTC") > load_splits()["test"].start)
    if needs_holdout and not period["use_holdout"]:
        st.info("Tick the holdout confirmation above to run on this period.")
        return
    if st.button("Run backtest", type="primary"):
        # Only send cost values that differ from the preset, so reports say
        # "customized" only when something was actually changed.
        changed = lambda v, d: None if abs(v - d) < 1e-12 else v  # noqa: E731
        opts = {"data": source.relative_to(REPO), "strategy": strategy, "params": params, "costs": costs,
                "fee_bps": changed(fee, preset.taker_fee * 1e4), "slippage_bps": changed(slip, preset.slippage_bps),
                "spread_bps": changed(spread, preset.spread_bps), "maker_share": changed(maker, preset.maker_fill_probability),
                "execution_price": exec_price, "latency_bars": latency, "capital": capital,
                "rebalance_threshold": band, "rebalance_hours": hours, "seeds": seeds, "benchmarks": benchmarks, **period}
        code, output = run_and_show(h.backtest_argv(opts), "Running backtest")
        found = h.parse_outputs(output)
        if code == 0 and "report" in found:
            st.session_state["bt_last"] = found
    last = st.session_state.get("bt_last")
    if last:
        show_backtest_result(last)


def show_backtest_result(found: dict) -> None:
    report = Path(found["report"])
    summary_path = report.parent / "summary.json"
    if summary_path.exists():
        s = json.loads(summary_path.read_text())
        n, g = s["net"], s["gross"]
        cols = st.columns(6)
        for col, (k, v) in zip(cols, [("Net return", f"{n['total_return']:+.2%}"), ("Gross return", f"{g['total_return']:+.2%}"),
                                      ("Sharpe (net)", f"{n['sharpe']:.2f}"), ("Max drawdown", f"{n['max_drawdown']:.2%}"),
                                      ("Composite", f"{n['composite']:.2f}"), ("Costs", f"${s['costs']['total_costs']:,.0f}")]):
            col.metric(k, v)
        st.caption(f"Run id `{found.get('run_id', '?')}` — reopen or reproduce it on the Run history page.")
        d1, d2, d3 = st.columns(3)
        for col, fname in zip((d1, d2, d3), ("summary.json", "trades.csv", "fills.csv")):
            f = report.parent / fname
            if f.exists():
                col.download_button(f"Download {fname}", f.read_bytes(), file_name=fname)
    embed_report(report)


def page_robustness() -> None:
    st.title("Robustness")
    st.write("Cost sensitivity, stress scenarios, Monte Carlo of 14-day outcomes, market regimes, parameter maps and "
             "the random-entry test, for the live strategy settings (or your own).")
    source = source_picker("rb_source")
    if source is None:
        return
    period = period_picker("rb", allow_custom=False)
    use_live = st.checkbox("Use the live strategy settings", True)
    params = None
    if not use_live:
        params = params_form("trend_vol_target", h.pairs_in(source), "rb")
    c1, c2, c3, c4 = st.columns(4)
    costs = c1.selectbox("Cost preset", list(SCENARIOS), index=list(SCENARIOS).index("base"), key="rb_costs")
    sims = c2.number_input("Monte Carlo paths per seed", min_value=100, value=2000, step=500)
    seeds_txt = c3.text_input("Monte Carlo seeds", "42, 123, 2026, 9999")
    sigma = c4.number_input("Cost uncertainty (lognormal σ)", value=0.25, step=0.05)
    c5, c6 = st.columns(2)
    rseeds = c5.number_input("Random-entry seeds", min_value=0, value=30, step=10)
    landscape = c6.checkbox("Parameter maps (slow: several minutes)", False)
    if period["split"] == "test" and not period["use_holdout"]:
        st.info("Tick the holdout confirmation above to run on this period.")
        return
    if st.button("Run robustness analysis", type="primary"):
        opts = {"data": source.relative_to(REPO), "split": period["split"], "use_holdout": period["use_holdout"],
                "costs": costs, "mc_sims": sims, "mc_seeds": [int(x) for x in seeds_txt.replace(",", " ").split()],
                "cost_sigma": sigma, "random_seeds": rseeds, "landscape": landscape, "params": params}
        code, output = run_and_show(h.robustness_argv(opts), "Running robustness analysis")
        found = h.parse_outputs(output)
        if code == 0 and "report" in found:
            st.session_state["rb_last"] = found
    last = st.session_state.get("rb_last")
    if last:
        st.caption(f"Run id `{last.get('run_id', '?')}`")
        embed_report(Path(last["report"]))


def page_history() -> None:
    st.title("Run history")
    reg = RunRegistry()
    runs = reg.list(limit=500)
    if not runs:
        st.info("No runs yet. Run a backtest first.")
        return
    table = pd.DataFrame([{"run id": r["run_id"], "kind": r["kind"], "created (UTC)": r["created_at"][:19],
                           "code": r["git_commit"][:8] + (" *" if r["git_dirty"] else ""),
                           **{k: (round(v, 4) if isinstance(v, float) else v) for k, v in (r["metrics"] or {}).items()}}
                          for r in runs])
    st.dataframe(table, width="stretch", hide_index=True)
    st.caption("* = run from uncommitted code")
    ids = [r["run_id"] for r in runs]
    chosen = st.selectbox("Open a run", ids)
    run = reg.get(chosen)
    c1, c2 = st.columns(2)
    with c1:
        st.markdown("**Command**")
        st.code(h.display_command(run["command"]), language="bash")
    with c2:
        st.markdown("**Configuration**")
        st.json(run["config"], expanded=False)
    b1, b2, b3 = st.columns([1, 1, 2])
    if b1.button("Reproduce this run"):
        run_and_show(["scripts/runs.py", "reproduce", chosen], "Reproducing")
    other = b3.selectbox("Compare with", [i for i in ids if i != chosen] or ["—"])
    if b2.button("Compare") and other != "—":
        run_and_show(["scripts/runs.py", "compare", chosen, other], "Comparing")
    out = Path(run["output_dir"])
    report = next((p for p in (out / "report.html", out / "robustness.html") if p.exists()), None)
    if report:
        embed_report(report)
    else:
        st.warning(f"The outputs of this run are gone ({out}); reproduce it to regenerate them.")


def page_bot() -> None:
    st.title("Paper bot")
    snap = h.bot_snapshot()
    if snap is None:
        st.info("No paper-bot data yet (data/state/bot-paper.sqlite3). Start it with `.venv/bin/python -m src.main`.")
        return
    if st.button("Refresh"):
        st.rerun()
    eq = snap["equity"]
    last = eq.iloc[-1] if len(eq) else None
    age = (pd.Timestamp.now(tz="UTC") - last.ts).total_seconds() / 60 if last is not None else None
    running = age is not None and age < 20
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Status", "running" if running else "stopped?", help="Based on the last equity snapshot (every 15 min).")
    c2.metric("Equity", f"${last.equity:,.0f}" if last is not None else "—", f"{last.equity / 1e5 - 1:+.3%}" if last is not None else None)
    c3.metric("Days with trades", len(snap["days"]))
    c4.metric("Orders", len(snap["orders"]))
    api = snap["api"]
    total = api.calls.sum()
    c5.metric("API success", f"{api.ok.sum() / total:.1%}" if total else "—", f"{int(api.failed.sum())} failed", delta_color="inverse")
    st.caption(f"Last snapshot {age:.0f} min ago" if age is not None else "")
    if len(eq):
        fig = go.Figure(go.Scatter(x=eq.ts, y=eq.equity, name="equity", line=dict(color="#60a5fa")))
        fig.add_hline(y=100_000, line=dict(dash="dot", color="gray"))
        fig.update_layout(height=320, margin=dict(l=40, r=10, t=20, b=30), yaxis_title="USD")
        st.plotly_chart(fig, width="stretch")
    st.subheader("Wallet (paper)")
    wallet = snap["wallet"] or {}
    st.dataframe(pd.DataFrame([{"asset": k, "quantity": round(v, 8)} for k, v in wallet.items()]), hide_index=True)
    st.subheader("Recent decisions (hourly)")
    st.dataframe(snap["decisions"], width="stretch", hide_index=True)
    st.subheader("Orders")
    st.dataframe(snap["orders"], width="stretch", hide_index=True)
    st.subheader("API calls")
    st.dataframe(api, width="stretch", hide_index=True)


page = st.sidebar.radio("Page", PAGES)
st.sidebar.caption("Local only · every run is reproducible from the terminal (see Run history).")
{"Overview": page_overview, "Data import": page_import, "Backtest": page_backtest, "Robustness": page_robustness,
 "Run history": page_history, "Paper bot": page_bot}[page]()
